// This file is generated by scripts/sync-github-projects.mjs.
// Do not edit it by hand. Edit GitHub repo topics or `.portfolio/project.json` instead.
export const githubProjects = [
	{
		"slug": "techzeph-website",
		"title": "TechZeph Portfolio",
		"status": "Built",
		"type": "Personal portfolio",
		"summary": "A static Astro portfolio that pulls project metadata from GitHub and presents repos as lightweight project pages.",
		"tags": [
			"Astro",
			"Tailwind CSS",
			"GitHub API",
			"Static site",
			"Portfolio"
		],
		"skills": [
			"Astro routing",
			"Static site generation",
			"Tailwind CSS",
			"GitHub API integration",
			"Generated project data",
			"Responsive UI components"
		],
		"complexity": {
			"level": "Layered",
			"score": 6,
			"signals": [
				"4 detected languages",
				"6 GitHub topics",
				"1,180 KB repository size"
			],
			"notes": "The project combines static Astro routes, generated GitHub data, theme state, reusable components, and documentation for future agent workflows."
		},
		"role": "Solo build with AI-assisted iteration",
		"currentState": "The site has core routes, theme controls, shared layout components, GitHub-synced project data, and documentation templates in place.",
		"learned": "Keeping project data normalized makes it easier to combine objective GitHub signals with richer human-written project context.",
		"next": "Add richer copy, screenshots, live project links, and more source repos with `.portfolio/project.json` metadata.",
		"repositoryUrl": "https://github.com/TechZeph/techzeph-website",
		"github": {
			"name": "techzeph-website",
			"fullName": "TechZeph/techzeph-website",
			"defaultBranch": "main",
			"language": "Astro",
			"languages": [
				{
					"name": "Astro",
					"bytes": 35002,
					"percentage": 62.6
				},
				{
					"name": "JavaScript",
					"bytes": 10145,
					"percentage": 18.1
				},
				{
					"name": "CSS",
					"bytes": 7498,
					"percentage": 13.4
				},
				{
					"name": "TypeScript",
					"bytes": 3313,
					"percentage": 5.9
				}
			],
			"topics": [
				"astro",
				"portfolio",
				"tailwindcss",
				"techzeph",
				"typescript",
				"web-development"
			],
			"sizeKb": 1180,
			"stars": 0,
			"forks": 0,
			"updatedAt": "2026-05-30T13:17:54Z",
			"pushedAt": "2026-05-30T13:17:51Z",
			"private": false,
			"archived": false
		}
	}
] as const;
