// This file is generated by scripts/sync-github-projects.mjs.
// Do not edit it by hand. Done items come from recent GitHub commits; edit repo topics, `.portfolio/project.json`, or `.portfolio/progress.json` for the rest.
export const githubProjects = [
	{
		"slug": "clanker-dev-agent",
		"title": "Clanker Dev Agent",
		"status": "Prototype",
		"type": "Developer workflow template",
		"summary": "A lightweight starter repo for documenting and sharing portfolio project metadata conventions. It currently provides reusable template files and guidance for adding richer project data to GitHub-backed portfolio entries.",
		"tags": [
			"Documentation",
			"GitHub",
			"Portfolio metadata",
			"Developer workflow"
		],
		"skills": [
			"Technical documentation",
			"Metadata modeling",
			"GitHub portfolio workflow",
			"Template design"
		],
		"complexity": {
			"level": "Focused",
			"score": 1,
			"signals": [
				"4 KB repository size"
			],
			"notes": "The repo is intentionally small and currently centers on reusable JSON metadata templates plus supporting documentation."
		},
		"role": "Solo build with AI-assisted iteration",
		"currentState": "The repository contains a minimal README and template documentation for generating portfolio project metadata.",
		"done": [
			"Add portfolio metadata template docs.",
			"Changed readme to markdown.",
			"Readme test."
		],
		"nextSteps": [
			"Expand the README with the repo purpose, setup notes, and an example of where the generated metadata should be copied or consumed."
		],
		"repositoryUrl": "https://github.com/TechZeph/clanker-dev-agent",
		"github": {
			"name": "clanker-dev-agent",
			"fullName": "TechZeph/clanker-dev-agent",
			"defaultBranch": "main",
			"language": "",
			"languages": [],
			"topics": [],
			"sizeKb": 4,
			"stars": 0,
			"forks": 0,
			"updatedAt": "2026-05-30T21:29:23Z",
			"pushedAt": "2026-05-30T21:29:10Z",
			"private": false,
			"archived": false
		}
	},
	{
		"slug": "techzeph-website",
		"title": "TechZeph Portfolio",
		"status": "Built",
		"type": "Personal portfolio",
		"summary": "A static Astro portfolio that pulls project metadata from GitHub and presents repos as lightweight project pages.",
		"tags": [
			"Astro",
			"Tailwind CSS",
			"GitHub API",
			"Static site",
			"Portfolio"
		],
		"skills": [
			"Astro routing",
			"Static site generation",
			"Tailwind CSS",
			"GitHub API integration",
			"Generated project data",
			"Responsive UI components"
		],
		"complexity": {
			"level": "Layered",
			"score": 6,
			"signals": [
				"4 detected languages",
				"6 GitHub topics",
				"1,278 KB repository size"
			],
			"notes": "The project combines static Astro routes, generated GitHub data, theme state, reusable components, and documentation for future agent workflows."
		},
		"role": "Solo build with AI-assisted iteration",
		"currentState": "The site has core routes, theme controls, shared layout components, GitHub-synced project data, and documentation templates in place.",
		"done": [
			"Derive portfolio progress from GitHub history.",
			"Refine theme system and project cards.",
			"Refine homepage portfolio copy.",
			"Pages:index grammar fix.",
			"Page:index none technical paragraph added to landing page."
		],
		"nextSteps": [
			"Add project-specific progress notes in `.portfolio/progress.json` inside the source repository."
		],
		"repositoryUrl": "https://github.com/TechZeph/techzeph-website",
		"github": {
			"name": "techzeph-website",
			"fullName": "TechZeph/techzeph-website",
			"defaultBranch": "main",
			"language": "Astro",
			"languages": [
				{
					"name": "Astro",
					"bytes": 38286,
					"percentage": 48.1
				},
				{
					"name": "CSS",
					"bytes": 22302,
					"percentage": 28
				},
				{
					"name": "JavaScript",
					"bytes": 12074,
					"percentage": 15.2
				},
				{
					"name": "TypeScript",
					"bytes": 7015,
					"percentage": 8.8
				}
			],
			"topics": [
				"astro",
				"portfolio",
				"tailwindcss",
				"techzeph",
				"typescript",
				"web-development"
			],
			"sizeKb": 1278,
			"stars": 0,
			"forks": 0,
			"updatedAt": "2026-06-02T20:38:41Z",
			"pushedAt": "2026-06-02T20:38:37Z",
			"private": false,
			"archived": false
		}
	}
] as const;
